version: '3.8'

services:
  # Frontend React App
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  # Backend Node.js API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=http://localhost
      - PORT=4000
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network

  # PostgreSQL Database (optional - remove if using external DB)
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=tik_logistics
      - POSTGRES_USER=tikadmin
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
  uploads:

networks:
  app-network:
    driver: bridge
